### ISSUE TITLE
Issue with LLMS and Memgraph docker compose

### ISSUE THREAD

**Issue by antejavor** [memgraph/documentation#555] opened 2024-03-08 13:50 UTC
Document the issue from discord thread: https://discord.com/channels/842007348272169002/890968976627228752/1215640019168006205

**Comment by kgolubic** [comment] 2024-03-18 08:33
@antejavor I was unable to reproduce the error. I've tried using Ollama both as a desktop app and within the Docker container. I've also used Docker and Docker compose to run the Memgraph MAGE docker image. Closing the issue. We can reopen if we get additional data.

**Comment by katarinasupe** [comment] 2024-04-10 13:34
As mentioned by the user host.docker.internal is needed on Mac or Windows if you have Lab running as a separate container from Memgraph/Memgraph MAGE. This should be noted [here](https://memgraph.com/docs/getting-started/install-memgraph/docker-compose#docker-compose-for-memgraph-platform) as well, as we talked about it on [Slack](https://memgraph.slack.com/archives/C068NCZU8PR/p1707988367818099?thread_ts=1707987238.156569&cid=C068NCZU8PR) (not sure where you added it, but I would add it to Docker Compose and GraphChat as the user mentioned).

**Comment by kgolubic** [comment] 2024-04-16 11:34
It is mentioned at https://memgraph.com/docs/getting-started/install-memgraph/docker#issues-when-connecting-to-memgraph-lab-to-memgraph.

This looks like an issue that has too many variables that influence the setup and results (OS, install method of Memgraph and Ollama, etc.). I think that the best approach for now would be to add Callouts to Docker Compose and GraphChat pages and to mention something along the lines "If you are having issues with connecting, try to use host.docker.internal instead of localhost or 127.0.0.1.".

I'll prepare PR for this.

**Closed** 2024-04-18 10:31 UTC
Labels: priority: medium (missing info)
