### ISSUE TITLE
Document meaning of notes upon Memgraph binary installation

### ISSUE THREAD

**Issue by vpavicic** [memgraph/documentation#99] opened 2023-09-01 12:21 UTC
When a user installs the Memgraph binary, they get a note about missing Python packages. It can be unclear to the user what this means and what to do next. We should document it better.
Here is the report: https://discord.com/channels/842007348272169002/842008652377751582/1124012471733190767
Here is the discussion to add to docs: https://memgraph.slack.com/archives/CSR01RS80/p1688056540942609

**Comment by kgolubic** [comment] 2023-12-29 14:45
Due to the [issues with WSL](https://github.com/memgraph/memgraph/issues/1551) I can't test this at the moment.

**Comment by kgolubic** [comment] 2024-01-29 14:30
I couldn't reproduce this on Ubuntu and Fedora running under WSL. Closing.

**Closed by kgolubic** 2024-01-29 14:30 UTC
Labels: priority: medium (missing info), status: waiting (blocked)
